/** Events generated by SDK internal detection (not from hardware directly). */
export const SDK = {
  DEVICE_STUCK: 'device-stuck',
  DEVICE_UNRESPONSIVE: 'device-unresponsive',
  DEVICE_RECOVERED: 'device-recovered',
  DEVICE_INTERACTION: 'device-interaction',
} as const;
