export type UnlockPolicy = 'none' | 'unlock-before-run' | 'retry-on-locked';

/**
 * Protocol V2 methods that are safe to replay after a locked response.
 *
 * Keep this as an exact allowlist. Name-pattern matching can silently make a new
 * state-changing method replayable when it happens to share a suffix.
 */
export const PROTOCOL_V2_RETRY_ON_LOCKED_METHODS = [
  'cipherKeyValue',
  'allNetworkGetAddress',
  'allNetworkGetAddressByLoop',
  'btcGetAddress',
  'btcGetPublicKey',
  'btcSignMessage',
  'btcSignPsbt',
  'btcSignTransaction',
  'btcVerifyMessage',
  'confluxGetAddress',
  'confluxSignMessage',
  'confluxSignTransaction',
  'evmGetAddress',
  'evmGetPublicKey',
  'evmSignMessage',
  'evmSignTransaction',
  'evmSignTypedData',
  'evmVerifyMessage',
  'starcoinGetAddress',
  'starcoinGetPublicKey',
  'starcoinSignMessage',
  'starcoinSignTransaction',
  'starcoinVerifyMessage',
  'nemGetAddress',
  'nemSignTransaction',
  'solGetAddress',
  'solSignTransaction',
  'solSignOffchainMessage',
  'solSignMessage',
  'stellarGetAddress',
  'stellarSignTransaction',
  'tronGetAddress',
  'tronSignMessage',
  'tronSignTransaction',
  'nearGetAddress',
  'nearSignTransaction',
  'aptosGetAddress',
  'aptosGetPublicKey',
  'aptosSignTransaction',
  'aptosSignMessage',
  'aptosSignInMessage',
  'algoGetAddress',
  'algoSignTransaction',
  'cosmosGetAddress',
  'cosmosGetPublicKey',
  'cosmosSignTransaction',
  'xrpGetAddress',
  'xrpSignTransaction',
  'suiGetAddress',
  'suiGetPublicKey',
  'suiSignMessage',
  'suiSignTransaction',
  'cardanoGetAddress',
  'cardanoGetPublicKey',
  'cardanoSignTransaction',
  'cardanoSignMessage',
  'filecoinGetAddress',
  'filecoinSignTransaction',
  'polkadotGetAddress',
  'polkadotSignTransaction',
  'kaspaGetAddress',
  'kaspaSignTransaction',
  'nexaGetAddress',
  'nexaSignTransaction',
  'nostrGetPublicKey',
  'nostrSignEvent',
  'nostrEncryptMessage',
  'nostrDecryptMessage',
  'nostrSignSchnorr',
  'lnurlAuth',
  'nervosGetAddress',
  'nervosSignTransaction',
  'dnxGetAddress',
  'dnxSignTransaction',
  'tonGetAddress',
  'tonSignMessage',
  'tonSignProof',
  'tonSignData',
  'scdoGetAddress',
  'scdoSignTransaction',
  'scdoSignMessage',
  'alephiumGetAddress',
  'alephiumSignTransaction',
  'alephiumSignMessage',
  'benfenGetAddress',
  'benfenGetPublicKey',
  'benfenSignMessage',
  'benfenSignTransaction',
  'neoGetAddress',
  'neoSignTransaction',
] as const;

const retryOnLockedMethods = new Set<string>(PROTOCOL_V2_RETRY_ON_LOCKED_METHODS);

export const getProtocolV2UnlockPolicy = (methodName: string): UnlockPolicy =>
  retryOnLockedMethods.has(methodName) ? 'retry-on-locked' : 'none';
