import type { btcGetOwnershipId } from './btcGetOwnershipId';
import type { btcGetOwnershipProof } from './btcGetOwnershipProof';
import type { btcAuthorizeCoinJoin } from './btcAuthorizeCoinJoin';
import type { cryptoBatchGetPublickeys } from './cryptoBatchGetPublickeys';
import type { cryptoCipherKeyValue } from './cryptoCipherKeyValue';
import type { cryptoCosiCommit } from './cryptoCosiCommit';
import type { cryptoCosiSign } from './cryptoCosiSign';
import type { cryptoGetECDHSessionKey } from './cryptoGetECDHSessionKey';
import type { cryptoSignIdentity } from './cryptoSignIdentity';
import type { evmGetAddressTrezor } from './evmGetAddressTrezor';
import type { evmGetPublicKeyTrezor } from './evmGetPublicKeyTrezor';
import type { evmSignMessageTrezor } from './evmSignMessageTrezor';
import type { evmSignTransactionTrezor } from './evmSignTransactionTrezor';
import type { evmSignTypedDataTrezor } from './evmSignTypedDataTrezor';
import type { evmVerifyMessageTrezor } from './evmVerifyMessageTrezor';
import type { nemDecryptMessage } from './nemDecryptMessage';
import type { deviceSpiFlashWrite } from './deviceSpiFlashWrite';
import type { deviceSpiFlashRead } from './deviceSpiFlashRead';
import type { devicePing } from './devicePing';
import type { deviceGetEntropy } from './deviceGetEntropy';
import type { deviceGetFirmwareHash } from './deviceGetFirmwareHash';
import type { deviceUnlockPath } from './deviceUnlockPath';
import type { deviceSdProtect } from './deviceSdProtect';
import type { deviceChangeWipeCode } from './deviceChangeWipeCode';
import type { deviceEndSession } from './deviceEndSession';
import type { deviceLoad } from './deviceLoad';
import type { deviceDoPreauthorized } from './deviceDoPreauthorized';
import type { deviceCancelAuthorization } from './deviceCancelAuthorization';
import type { emmcDirList } from './emmcDirList';
import type { emmcDirMake } from './emmcDirMake';
import type { emmcDirRemove } from './emmcDirRemove';
import type { emmcFileDelete } from './emmcFileDelete';
import type { emmcFileRead } from './emmcFileRead';
import type { emmcFileWrite } from './emmcFileWrite';
import type { emmcFixPermission } from './emmcFixPermission';
import type { emmcPathInfo } from './emmcPathInfo';
import type { debugLinkDecision } from './debugLinkDecision';
import type { debugLinkEraseSdCard } from './debugLinkEraseSdCard';
import type { debugLinkFlashErase } from './debugLinkFlashErase';
import type { debugLinkGetState } from './debugLinkGetState';
import type { debugLinkMemoryRead } from './debugLinkMemoryRead';
import type { debugLinkMemoryWrite } from './debugLinkMemoryWrite';
import type { debugLinkRecordScreen } from './debugLinkRecordScreen';
import type { debugLinkReseedRandom } from './debugLinkReseedRandom';
import type { debugLinkStop } from './debugLinkStop';
import type { debugLinkWatchLayout } from './debugLinkWatchLayout';
import type { firmwareErase } from './firmwareErase';
import type { firmwareEraseEx } from './firmwareEraseEx';
import type { firmwareUpdateEmmcTest } from './firmwareUpdateEmmcTest';
import type { firmwareUploadTest } from './firmwareUploadTest';
import type { reboot } from './reboot';
import type { selfTest } from './selfTest';
import type { tezosGetAddress } from './tezosGetAddress';
import type { tezosGetPublicKey } from './tezosGetPublicKey';
import type { tezosSignTx } from './tezosSignTx';
import type { moneroGetAddress } from './moneroGetAddress';
import type { moneroGetWatchKey } from './moneroGetWatchKey';
import type { eosGetPublicKey } from './eosGetPublicKey';
import type { eosSignTx } from './eosSignTx';
import type { binanceGetAddress } from './binanceGetAddress';
import type { binanceGetPublicKey } from './binanceGetPublicKey';
import type { binanceSignTx } from './binanceSignTx';
import type { webAuthnAddResidentCredential } from './webAuthnAddResidentCredential';
import type { webAuthnListResidentCredentials } from './webAuthnListResidentCredentials';
import type { webAuthnRemoveResidentCredential } from './webAuthnRemoveResidentCredential';
import type { getPublicKeyMultiple } from './getPublicKeyMultiple';
import type { listResDir } from './listResDir';
import type { nftWriteData } from './nftWriteData';
import type { nftWriteInfo } from './nftWriteInfo';
import type { readSEPublicKey } from './readSEPublicKey';
import type { resourceUpdate } from './resourceUpdate';
import type { bixinBackupDevice } from './bixinBackupDevice';
import type { bixinLoadDevice } from './bixinLoadDevice';
import type { bixinMessageSE } from './bixinMessageSE';
import type { bixinVerifyDeviceRequest } from './bixinVerifyDeviceRequest';

export type TestApiMethods = {
  btcGetOwnershipId: typeof btcGetOwnershipId;
  btcGetOwnershipProof: typeof btcGetOwnershipProof;
  btcAuthorizeCoinJoin: typeof btcAuthorizeCoinJoin;
  cryptoBatchGetPublickeys: typeof cryptoBatchGetPublickeys;
  cryptoCipherKeyValue: typeof cryptoCipherKeyValue;
  cryptoCosiCommit: typeof cryptoCosiCommit;
  cryptoCosiSign: typeof cryptoCosiSign;
  cryptoGetECDHSessionKey: typeof cryptoGetECDHSessionKey;
  cryptoSignIdentity: typeof cryptoSignIdentity;
  evmGetAddressTrezor: typeof evmGetAddressTrezor;
  evmGetPublicKeyTrezor: typeof evmGetPublicKeyTrezor;
  evmSignMessageTrezor: typeof evmSignMessageTrezor;
  evmSignTransactionTrezor: typeof evmSignTransactionTrezor;
  evmSignTypedDataTrezor: typeof evmSignTypedDataTrezor;
  evmVerifyMessageTrezor: typeof evmVerifyMessageTrezor;
  nemDecryptMessage: typeof nemDecryptMessage;
  deviceSpiFlashWrite: typeof deviceSpiFlashWrite;
  deviceSpiFlashRead: typeof deviceSpiFlashRead;
  devicePing: typeof devicePing;
  deviceGetEntropy: typeof deviceGetEntropy;
  deviceGetFirmwareHash: typeof deviceGetFirmwareHash;
  deviceUnlockPath: typeof deviceUnlockPath;
  deviceSdProtect: typeof deviceSdProtect;
  deviceChangeWipeCode: typeof deviceChangeWipeCode;
  deviceEndSession: typeof deviceEndSession;
  deviceLoad: typeof deviceLoad;
  deviceDoPreauthorized: typeof deviceDoPreauthorized;
  deviceCancelAuthorization: typeof deviceCancelAuthorization;
  emmcDirList: typeof emmcDirList;
  emmcDirMake: typeof emmcDirMake;
  emmcDirRemove: typeof emmcDirRemove;
  emmcFileDelete: typeof emmcFileDelete;
  emmcFileRead: typeof emmcFileRead;
  emmcFileWrite: typeof emmcFileWrite;
  emmcFixPermission: typeof emmcFixPermission;
  emmcPathInfo: typeof emmcPathInfo;
  debugLinkDecision: typeof debugLinkDecision;
  debugLinkEraseSdCard: typeof debugLinkEraseSdCard;
  debugLinkFlashErase: typeof debugLinkFlashErase;
  debugLinkGetState: typeof debugLinkGetState;
  debugLinkMemoryRead: typeof debugLinkMemoryRead;
  debugLinkMemoryWrite: typeof debugLinkMemoryWrite;
  debugLinkRecordScreen: typeof debugLinkRecordScreen;
  debugLinkReseedRandom: typeof debugLinkReseedRandom;
  debugLinkStop: typeof debugLinkStop;
  debugLinkWatchLayout: typeof debugLinkWatchLayout;
  firmwareErase: typeof firmwareErase;
  firmwareEraseEx: typeof firmwareEraseEx;
  firmwareUpdateEmmcTest: typeof firmwareUpdateEmmcTest;
  firmwareUploadTest: typeof firmwareUploadTest;
  reboot: typeof reboot;
  selfTest: typeof selfTest;
  tezosGetAddress: typeof tezosGetAddress;
  tezosGetPublicKey: typeof tezosGetPublicKey;
  tezosSignTx: typeof tezosSignTx;
  moneroGetAddress: typeof moneroGetAddress;
  moneroGetWatchKey: typeof moneroGetWatchKey;
  eosGetPublicKey: typeof eosGetPublicKey;
  eosSignTx: typeof eosSignTx;
  binanceGetAddress: typeof binanceGetAddress;
  binanceGetPublicKey: typeof binanceGetPublicKey;
  binanceSignTx: typeof binanceSignTx;
  webAuthnAddResidentCredential: typeof webAuthnAddResidentCredential;
  webAuthnListResidentCredentials: typeof webAuthnListResidentCredentials;
  webAuthnRemoveResidentCredential: typeof webAuthnRemoveResidentCredential;
  getPublicKeyMultiple: typeof getPublicKeyMultiple;
  listResDir: typeof listResDir;
  nftWriteData: typeof nftWriteData;
  nftWriteInfo: typeof nftWriteInfo;
  readSEPublicKey: typeof readSEPublicKey;
  resourceUpdate: typeof resourceUpdate;
  bixinBackupDevice: typeof bixinBackupDevice;
  bixinLoadDevice: typeof bixinLoadDevice;
  bixinMessageSE: typeof bixinMessageSE;
  bixinVerifyDeviceRequest: typeof bixinVerifyDeviceRequest;
};
