name: Build and Deploy Examples

on:
  workflow_dispatch

jobs:
  build_expo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: |
          yarn
          yarn bootstrap
      - name: Build Expo Example
        run: yarn expo export:web
        working-directory: packages/connect-examples/expo-example
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-build
          path: packages/connect-examples/expo-example/web-build

  build_new_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: yarn
      - name: Build New Example
        run: VITE_COMMIT_SHA=${GITHUB_SHA:0:7} yarn workspace onekeyexample run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-example-build
          path: packages/connect-examples/new-example/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build_expo, build_new_example]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deploy Directory
        run: mkdir -p deploy
      - name: Download Expo Artifact
        uses: actions/download-artifact@v4
        with:
          name: expo-build
          path: deploy/expo-example
      - name: Download New Example Artifact
        uses: actions/download-artifact@v4
        with:
          name: new-example-build
          path: deploy/new-example
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: example.onekey-test.com
          force_orphan: true
