name: test_web

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TEST_ENDPOINT: hardware-example.onekeytest.com
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Package
        run: |
          yarn
          yarn bootstrap
      - name: Build Target
        run: |
          yarn build
          cd packages/connect-examples/expo-example
          npx expo export:web

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/connect-examples/expo-example/web-build
          cname: ${{ env.TEST_ENDPOINT }}
          force_orphan: true
