name: release-web

on: workflow_dispatch

jobs:
  test-web:
    runs-on: ubuntu-latest
    env:
      HOST_PATH: '${{ github.event.repository.name }}/${{ github.sha }}/'
      PUBLIC_URL: 'https://hardware-sdk.onekey.so/'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Package
        run: |
          yarn
          yarn bootstrap
      - name: Build Target
        run: |
          yarn build

      - name: Build Target
        env:
          PUBLIC_URL: ${{ env.PUBLIC_URL }}
        run: |
          yarn build

      - name: Deploy to CDN
        uses: OneKeyHQ/onekey-github-actions/s3-upload@main
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './packages/hd-web-sdk/build/'
          destination_dir: ${{ env.HOST_PATH }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hardware-sdk-${{ github.sha }}
          path: |
            ./packages/hd-web-sdk/build/
