name: deploy-release-iframe-web

on: workflow_dispatch

jobs:
  release-web:
    runs-on: ubuntu-latest
    env:
      PUBLIC_PATH: 'https://jssdk.onekey.so/${{ github.event.repository.name }}/${{ github.sha }}/'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Package
        run: |
          yarn
          yarn bootstrap
      - name: Build Target
        env:
          PUBLIC_PATH: ${{ env.PUBLIC_PATH }}
        run: |
          yarn build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hardware-sdk-${{ github.sha }}
          path: |
            ./packages/hd-web-sdk/build/
